export const SET_PROVIDER_NAME = 'setProviderName'
export const SET_CONFIGS = 'setConfigs'
export const SET_UPLOADED = 'setUploaded'
export const ADD_UPLOAD = 'addUpload'
export const REMOVE_UPLOAD = 'removeUpload'
