export const SET_PROVIDER_NAME = 'setProviderName'
export const SET_CONFIGS = 'setConfigs'
export const SET_UPLOADED = 'setUploaded'
export const ADD_UPLOADED = 'addUploaded'
export const REMOVE_UPLOADED = 'removeUploaded'
export const SET_UPLOADING = 'setUploading'
export const REMOVE_UPLOADING = 'removeUploading'
