export const SET_PROVIDER_NAME = 'setProviderName'
export const SET_CONFIGS = 'setConfigs'
export const SET_UPLOADED = 'setUploaded'
export const UPLOAD_PROGRESS = 'updateProgress'
export const UPLOAD_SUCCESS = 'uploadSUCCESS'
export const UPLOAD_ERROR = 'uploadError'
